name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write  
    steps:
      - uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install nodejs dependencies
        run: |
          yarn production
      - name: Commit
        run: |
          git config --local user.name "Yukie-Billal"
          git config --local user.email "yukiembillal01@gmail.com"
          git add .
          git commit -m "[AUTO:BUILD] build from src/main.js"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: "main"
          repository: "yukie-billal/github-actions-testing"
